/*
 * This source file was generated by the Gradle 'init' task
 */
package slyde;

import slyde.compiler.Compiler;

public class App {
    public static void main(String[] args) {
        Compiler.compile(null, null);
    }
}
